const baseUri = "http://www.w3.org/2001/XMLSchema#";

export const XSD = {
  string: baseUri.concat("string"),
  boolean: baseUri.concat("boolean"),
  decimal: baseUri.concat("decimal"),
  integer: baseUri.concat("integer"),
  double: baseUri.concat("double"),
  float: baseUri.concat("float"),
  date: baseUri.concat("date"),
  time: baseUri.concat("time"),
  dateTime: baseUri.concat("dateTime"),
  dateTimeStamp: baseUri.concat("dateTimeStamp"),
  gYear: baseUri.concat("gYear"),
  gMonth: baseUri.concat("gMonth"),
  gDay: baseUri.concat("gDay"),
  gYearMonth: baseUri.concat("gYearMonth"),
  gMonthDay: baseUri.concat("gMonthDay"),
  duration: baseUri.concat("duration"),
  yearMonthDuration: baseUri.concat("yearMonthDuration"),
  dayTimeDuration: baseUri.concat("dayTimeDuration"),
  byte: baseUri.concat("byte"),
  short: baseUri.concat("short"),
  int: baseUri.concat("int"),
  long: baseUri.concat("long"),
  unsignedByte: baseUri.concat("unsignedByte"),
  unsignedShort: baseUri.concat("unsignedShort"),
  unsignedInt: baseUri.concat("unsignedInt"),
  unsignedLong: baseUri.concat("unsignedLong"),
  positiveInteger: baseUri.concat("positiveInteger"),
  nonNegativeInteger: baseUri.concat("nonNegativeInteger"),
  negativeInteger: baseUri.concat("negativeInteger"),
  nonPositiveInteger: baseUri.concat("nonPositiveInteger"),
  hexBinary: baseUri.concat("hexBinary"),
  base64Binary: baseUri.concat("base64Binary"),
  anyURI: baseUri.concat("anyURI"),
  language: baseUri.concat("language"),
  normalizedString: baseUri.concat("normalizedString"),
  token: baseUri.concat("token"),
  NMTOKEN: baseUri.concat("NMTOKEN"),
  Name: baseUri.concat("Name"),
  NCName: baseUri.concat("NCName"),
}
